package comm;


/**
* comm/_GhostListenerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ghost.idl
* Terça-feira, 18 de Novembro de 2008 20h47min30s GMT-03:00
*/

public class _GhostListenerStub extends org.omg.CORBA.portable.ObjectImpl implements comm.GhostListener
{

  public void worldInfo (org.omg.CORBA.StringHolder matrix)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("worldInfo", true);
                $in = _invoke ($out);
                matrix.value = $in.read_string ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                worldInfo (matrix        );
            } finally {
                _releaseReply ($in);
            }
  } // worldInfo

  public void pacManInfo (org.omg.CORBA.ShortHolder x, org.omg.CORBA.ShortHolder y)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("pacManInfo", true);
                $in = _invoke ($out);
                x.value = $in.read_short ();
                y.value = $in.read_short ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                pacManInfo (x, y        );
            } finally {
                _releaseReply ($in);
            }
  } // pacManInfo

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:comm/GhostListener:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _GhostListenerStub
