package comm;


/**
* comm/_GhostServerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ghost.idl
* Sexta-feira, 14 de Novembro de 2008 19h11min49s GMT-03:00
*/

public class _GhostServerStub extends org.omg.CORBA.portable.ObjectImpl implements comm.GhostServer
{

  public void register (comm.GhostListener listener)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("register", true);
                comm.GhostListenerHelper.write ($out, listener);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                register (listener        );
            } finally {
                _releaseReply ($in);
            }
  } // register

  public boolean ghostInfo (short id, org.omg.CORBA.ShortHolder x, org.omg.CORBA.ShortHolder y)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ghostInfo", true);
                $out.write_short (id);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                x.value = $in.read_short ();
                y.value = $in.read_short ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ghostInfo (id, x, y        );
            } finally {
                _releaseReply ($in);
            }
  } // ghostInfo

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:comm/GhostServer:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _GhostServerStub
