package comm;


/**
* comm/GhostListenerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ghost.idl
* Sexta-feira, 14 de Novembro de 2008 19h11min49s GMT-03:00
*/

public interface GhostListenerOperations 
{
  void worldInfo (org.omg.CORBA.StringHolder matrix);
  void pacManInfo (org.omg.CORBA.ShortHolder x, org.omg.CORBA.ShortHolder y);
} // interface GhostListenerOperations
