package comm;


/**
* comm/GhostServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ghost.idl
* Sábado, 6 de Dezembro de 2008 11h09min04s GMT-03:00
*/

public interface GhostServerOperations 
{
  short ghostInfo (short id, org.omg.CORBA.ShortHolder x, org.omg.CORBA.ShortHolder y);
  short worldId ();
  void worldInfo (short id, String map, short width, short height);
  void pacManInfo (short id, short x, short y);
} // interface GhostServerOperations
