package comm;


/**
* comm/GhostServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ghost.idl
* Terça-feira, 18 de Novembro de 2008 20h47min30s GMT-03:00
*/

public interface GhostServerOperations 
{
  void register (comm.GhostListener listener);
  boolean ghostInfo (short id, org.omg.CORBA.ShortHolder x, org.omg.CORBA.ShortHolder y);
} // interface GhostServerOperations
