package comm;


/**
* comm/GhostListenerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ghost.idl
* Sexta-feira, 14 de Novembro de 2008 19h11min49s GMT-03:00
*/

public abstract class GhostListenerPOA extends org.omg.PortableServer.Servant
 implements comm.GhostListenerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("worldInfo", new java.lang.Integer (0));
    _methods.put ("pacManInfo", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // comm/GhostListener/worldInfo
       {
         org.omg.CORBA.StringHolder matrix = new org.omg.CORBA.StringHolder ();
         this.worldInfo (matrix);
         out = $rh.createReply();
         out.write_string (matrix.value);
         break;
       }

       case 1:  // comm/GhostListener/pacManInfo
       {
         org.omg.CORBA.ShortHolder x = new org.omg.CORBA.ShortHolder ();
         org.omg.CORBA.ShortHolder y = new org.omg.CORBA.ShortHolder ();
         this.pacManInfo (x, y);
         out = $rh.createReply();
         out.write_short (x.value);
         out.write_short (y.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:comm/GhostListener:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GhostListener _this() 
  {
    return GhostListenerHelper.narrow(
    super._this_object());
  }

  public GhostListener _this(org.omg.CORBA.ORB orb) 
  {
    return GhostListenerHelper.narrow(
    super._this_object(orb));
  }


} // class GhostListenerPOA
