package comm;


/**
* comm/GhostListener.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ghost.idl
* Terça-feira, 18 de Novembro de 2008 20h47min30s GMT-03:00
*/

public interface GhostListener extends GhostListenerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GhostListener
