package comm;


/**
* comm/GhostServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ghost.idl
* Sexta-feira, 14 de Novembro de 2008 19h11min49s GMT-03:00
*/

public interface GhostServer extends GhostServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GhostServer
