package br.pacmen.ghost.corba.comm;


/**
* comm/GhostServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ghost.idl
* Segunda-feira, 8 de Dezembro de 2008 00h12min01s GMT-03:00
*/

public interface GhostServer extends GhostServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GhostServer
