package br.pacmen.world.rpc.comm;

//Generated by Netbula JRPCGEN V2.5.6.
//Netbula JavaRPC demo, expires after a fixed date!



import netbula.ORPC.*;

public class st_ActorAndNext implements XDT{
	public st_Actor actor = new st_Actor();
	public short next;

	public XDT Clone() { return new st_ActorAndNext();}

	public XDT [] getArray(int len) { return new st_ActorAndNext[len];}

	public void xdr(XDR xdrs) throws XDRError{
		switch(xdrs.xdr_op){
		case XDR.XDR_ENCODE:
		actor.xdr(xdrs);
		xdrs.enc_short(next);
		break;

		case XDR.XDR_DECODE:
		actor.xdr(xdrs);
		next = xdrs.dec_short();
		break;

		}
	}
};
