package comm;

/**
* comm/GhostListenerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ghost.idl
* Terça-feira, 18 de Novembro de 2008 20h47min30s GMT-03:00
*/

public final class GhostListenerHolder implements org.omg.CORBA.portable.Streamable
{
  public comm.GhostListener value = null;

  public GhostListenerHolder ()
  {
  }

  public GhostListenerHolder (comm.GhostListener initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = comm.GhostListenerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    comm.GhostListenerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return comm.GhostListenerHelper.type ();
  }

}
