package comm;

/**
* comm/GhostServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ghost.idl
* Sexta-feira, 21 de Novembro de 2008 19h31min46s GMT-03:00
*/

public final class GhostServerHolder implements org.omg.CORBA.portable.Streamable
{
  public comm.GhostServer value = null;

  public GhostServerHolder ()
  {
  }

  public GhostServerHolder (comm.GhostServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = comm.GhostServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    comm.GhostServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return comm.GhostServerHelper.type ();
  }

}
