package comm;


/**
* comm/GhostServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ghost.idl
* Sábado, 6 de Dezembro de 2008 11h09min04s GMT-03:00
*/

public interface GhostServer extends GhostServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GhostServer
