package comm;


/**
* comm/GhostServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ghost.idl
* Sexta-feira, 21 de Novembro de 2008 19h31min46s GMT-03:00
*/

public interface GhostServerOperations 
{
  short ghostInfo (short id, org.omg.CORBA.ShortHolder x, org.omg.CORBA.ShortHolder y);
  short worldId ();
  void worldInfo (String matrix);
  void pacManInfo (short x, short y);
} // interface GhostServerOperations
