module comm {


  interface GhostServer {

    short ghostInfo(in short id, out short x, out short y);
    short worldId();
    void worldInfo(in string matrix);
    void pacManInfo(in short x, in short y);

  };


};
