package br.pacmen.world.rpc.comm;

//Generated by Netbula JRPCGEN V2.5.6.
//Netbula JavaRPC demo, expires after a fixed date!



import netbula.ORPC.Svc;
import netbula.ORPC.XDR;
import netbula.ORPC.XDRError;
import netbula.ORPC.XDT;
import netbula.ORPC.XDTshort;
import netbula.ORPC.XDTvoid;

abstract public class PacMen_svcb extends Svc implements PacMen {

	public PacMen_svcb(int prog, int ver) {
		super(prog, ver);
	}

	public PacMen_svcb() {
		super(PacMen._def_pno, PacMen._def_vno);
	}

	abstract public st_World worldInfo() ;

	abstract public st_Status pacManInfo(st_Actor in_arg) ;

	abstract public st_ActorAndNext ghostInfo(short in_arg) ;

	public XDT proc_call (int proc, XDR inXDR) throws XDRError {
		switch(proc) {
		case 0: return new XDTvoid();

		case 1:
		st_World _out_arg1;
		_out_arg1 = this.worldInfo();
		return _out_arg1;

		case 2:
		st_Status _out_arg2;
		try {
			st_Actor _in_arg = new st_Actor();
			_in_arg.xdr(inXDR);
			_out_arg2 = this.pacManInfo(_in_arg);
		} catch (XDRError e) {
			throw e;
		}
		return _out_arg2;

		case 3:
		st_ActorAndNext _out_arg3;
		try {
			XDTshort _in_arg = new XDTshort();
			_in_arg.xdr(inXDR);
			_out_arg3 = this.ghostInfo(_in_arg.value);
		} catch (XDRError e) {
			throw e;
		}
		return _out_arg3;

		default: return null;
		}
	}

}

