package br.pacmen.world.rpc.comm;

//Generated by Netbula JRPCGEN V2.5.6.
//Netbula JavaRPC demo, expires after a fixed date!



import netbula.ORPC.*;

public class st_Actor implements XDT{
	public short id;
	public short x;
	public short y;

	public XDT Clone() { return new st_Actor();}

	public XDT [] getArray(int len) { return new st_Actor[len];}

	public void xdr(XDR xdrs) throws XDRError{
		switch(xdrs.xdr_op){
		case XDR.XDR_ENCODE:
		xdrs.enc_short(id);
		xdrs.enc_short(x);
		xdrs.enc_short(y);
		break;

		case XDR.XDR_DECODE:
		id = xdrs.dec_short();
		x = xdrs.dec_short();
		y = xdrs.dec_short();
		break;

		}
	}
};
