package br.pacmen.ghost.corba.comm;


/**
* comm/_GhostServerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ghost.idl
* Segunda-feira, 8 de Dezembro de 2008 00h12min01s GMT-03:00
*/

public class _GhostServerStub extends org.omg.CORBA.portable.ObjectImpl implements br.pacmen.ghost.corba.comm.GhostServer
{

  public short ghostInfo (short id, org.omg.CORBA.ShortHolder x, org.omg.CORBA.ShortHolder y)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ghostInfo", true);
                $out.write_short (id);
                $in = _invoke ($out);
                short $result = $in.read_short ();
                x.value = $in.read_short ();
                y.value = $in.read_short ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ghostInfo (id, x, y        );
            } finally {
                _releaseReply ($in);
            }
  } // ghostInfo

  public short firstGhostInfo ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("firstGhostInfo", true);
                $in = _invoke ($out);
                short $result = $in.read_short ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return firstGhostInfo (        );
            } finally {
                _releaseReply ($in);
            }
  } // firstGhostInfo

  public short worldId ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("worldId", true);
                $in = _invoke ($out);
                short $result = $in.read_short ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return worldId (        );
            } finally {
                _releaseReply ($in);
            }
  } // worldId

  public void worldInfo (short id, String map, short width, short height)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("worldInfo", true);
                $out.write_short (id);
                $out.write_string (map);
                $out.write_short (width);
                $out.write_short (height);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                worldInfo (id, map, width, height        );
            } finally {
                _releaseReply ($in);
            }
  } // worldInfo

  public void pacManInfo (short id, short x, short y)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("pacManInfo", true);
                $out.write_short (id);
                $out.write_short (x);
                $out.write_short (y);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                pacManInfo (id, x, y        );
            } finally {
                _releaseReply ($in);
            }
  } // pacManInfo

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:comm/GhostServer:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _GhostServerStub
