package br.pacmen.ghost.corba.comm;

/**
* comm/GhostServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ghost.idl
* Segunda-feira, 8 de Dezembro de 2008 00h12min01s GMT-03:00
*/

public final class GhostServerHolder implements org.omg.CORBA.portable.Streamable
{
  public br.pacmen.ghost.corba.comm.GhostServer value = null;

  public GhostServerHolder ()
  {
  }

  public GhostServerHolder (br.pacmen.ghost.corba.comm.GhostServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.pacmen.ghost.corba.comm.GhostServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.pacmen.ghost.corba.comm.GhostServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.pacmen.ghost.corba.comm.GhostServerHelper.type ();
  }

}
